name: Lint
on: [workflow_dispatch, pull_request]
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - name: Setup Node
      uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a
    - run: npm ci --ignore-scripts
    - run: npm run lint --silent
